# Generated by Django 5.2 on 2025-06-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mealplan",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="mealplan",
            name="updated_at",
        ),
    ]
