# Generated by Django 5.2 on 2025-05-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_unit_mealplan_recipe_ingredient_usermealplan_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="recipe",
        ),
    ]
