# Generated by Django 5.2 on 2025-05-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_recipeingredient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="symbol",
        ),
        migrations.AddField(
            model_name="unit",
            name="abbreviation",
            field=models.CharField(default="kg", max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="unit",
            name="category",
            field=models.CharField(
                choices=[
                    ("weight", "Weight"),
                    ("volume", "Volume"),
                    ("count", "Count"),
                    ("length", "Length"),
                    ("time", "Time"),
                    ("temp", "Temperature"),
                    ("area", "Area"),
                    ("hybrid", "Volume-Weight Hybrid"),
                ],
                default="weight",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="conversion_factor",
            field=models.FloatField(
                default=1.0, help_text="Conversion factor to base unit"
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
